import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./component/Footer";

import Navbar from "./component/Navbar";
import Option1 from "./component/option1";
import Option2 from "./component/Option2";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        < Navbar />
        <Option1 /> 
        <Option2 />   
        {children}
        <Footer/>
        </body>
    </html>
  );
}
